### ISSUE TITLE
Make code available when import to objective C via Pod

### ISSUE THREAD

**Issue by baohung02** [tkach/PinCodeTextField#1]
I tried to import this to my objective C proj via Pod. I couldn't work without insert '@objc' to your code.
So, can you make it available for Objective C prj with Pod imported.
Thanks.

**Comment by tkach** [comment]
@baohung02 Thanks for reporting the issue. 
Haven't tested it in Objective-C, so I'll take a look.

**Comment by tkach** [comment]
It seems that problem of linking PinCodeTextField into Obj-C project is that I use many swift-only features, such as protocol and class extensions (in PinCodeTextField, PinCodeTextFieldDelegate). 
So it's needed to rewrite it a little bit in order to make it available for Objective-C. 
Maybe you know some easier way to make it work?

**Comment by baohung02** [comment]
I edited 2 lines as same as below 

>**public** weak var delegate: PinCodeTextFieldDelegate?

> **@objc** public protocol PinCodeTextFieldDelegate: class {

It works well, I just worked with swift little time, so this is my resolution. If you have any ideas, let tell me. :]

**Comment by tkach** [comment]
@baohung02 Awesome! Thanks for helping to fix it! 👍 
One problem with @objc protocols in Swift projects is that it's not very convenient in Swift-only projects (if you wish to implement PinCodeTextFieldDelegate protocol, your class should be the subclass of NSObject).
That's why I've created 2 subspecs, one for using in Swift projects, another for Objective-C.
So please change your Podfile and use this line:
`pod 'PinCodeTextField/ObjC', :git => "https://github.com/tkach/PinCodeTextField"`
In Swift projects you just use default subspec:
`pod 'PinCodeTextField', :git => "https://github.com/tkach/PinCodeTextField"`

**Comment by baohung02** [comment]
Thanks for your quickly support <3
