### ISSUE TITLE
Swift 4 Pod Integration issue

### ISSUE THREAD

**Issue by saqibomer** [tkach/PinCodeTextField#14]
Add `import PinCodeTextField` in example `ViewController.Swift`

**Comment by tkach** [comment]
Hi, PinCodeTextField library is linked by adding sources to example project. 
We don't need `import PinCodeTextField` because ViewController is in the same module with PinCodeTextField. Actually compiler gives a warning about importing the same module in such case.
Of course, if library had been added via Cocoapods or Carthage, we would need to import it (in that scenario it's linked as a separate module).

**Comment by saqibomer** [comment]
Ahh I see. Thanks, :)
